### ISSUE TITLE
Support x86 for Avisynth

### ISSUE THREAD

**Issue by kedaitinh12** [Irrational-Encoding-Wizardry/vapoursynth-descale#4]
Can you support it for Avisynth x86??

**Comment by Frechdachs** [comment]
To be honest, I have no intention to officially support 32-bit, but here's a build:
[avisynth-descale-r8-win32.zip](https://github.com/Irrational-Encoding-Wizardry/descale/files/8405290/avisynth-descale-r8-win32.zip)
I have not tested it, so no idea if it works.

For reference here is the cross file I used it to compile with:
```
[binaries]
c = 'i686-w64-mingw32-gcc'
cpp = 'i686-w64-mingw32-g++'
ar = 'i686-w64-mingw32-ar'
strip = 'i686-w64-mingw32-strip'
pkgconfig = 'i686-w64-mingw32-pkg-config'

[host_machine]
system = 'windows'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'

[properties]
c_args = ['-march=i686', '-mtune=generic', '-O2']
c_link_args = ['-s']
```

Out of interest, what is the reason you are still on a 32-bit operating system?

BTW, this plugin is explicitly only for AviSynth+, because it uses functions only available in the newer API.
If you are still on an older version of AviSynth, then this build will definitely not work.

**Comment by kedaitinh12** [comment]
Cause it's Avisynth. Many people still use 32bit ver in 64bit operating system cause many 32bit plugins don't have 64bit ver (Vapoursynth use 64bit ver plugins cause it's newer than Avisynth). I think if you port your plugin to Avisynth you need support both x86 and x64 ver. Sorry for inconvenient in Avisynth and thanks for x86 binary ver😂😂😂
